[general]
auto_append = false

[ipc]
ipc_enabled_commands = [
  "mc",  # activate normal casing
  "sc",  # activate snake_casing
  "pm",  # activate ProperCasing
  "cm",  # activate camelCasing
  "us",  # activate UPPER_SNAKE_CASING
  "cb",  # clear buffer
  "sm",  # set main buffer
  "sr",  # set right buffer
  # "rl",  # reload config
  # "rs",  # restart program
]

[chunking]
new_chunks_only = true

[code]
spacing_type = "new"
space_on_new = false

[chips]
"rl" = ["reload_config"]
"-" = ["kebab-case-mode"]
# "nm" = ["normal case mode"]
"_" = ["snake_case_mode"]
"__" = ["UPPER_SNAKE_CASE_MODE"]
".." = ["backspace", ".", ".", ".", "space"]
"pm" = ["ProperCaseMode"]
"cmm" = ["camelCaseMode"]
"ras" = ["restart"]
"'s" = ["backspace", "'", "s", "space"]
"'t" = ["backspace", "n", "'", "t", "space"]
"'l" = ["backspace", "'", "l", "l", "space"]
"'d" = ["backspace", "'", "d", "space"]
"at" = "at"
"it" = "it"
"in" = "in"
"is" = "is"
"of" = "of"
"to" = "to"
"so" = "so"
"be" = "be"
"into" = "into"
"do" = "do"
"us" = "us"
"an" = "an"
"by" = "by"
"up" = "up"
"or" = "or"
"go" = "go"
"sog" = "goes"
"gm" = "got"
"ggm" = "game"
"wel" = "well"
"lak" = "look"
"maa" = "may"
"whh" = "why"
"itt" = "its"
"bnn" = "being"
"htt" = "heart"
"he" = "he"
"me" = "me"
"if" = "if"
"we" = "we"
"as" = "as"
"ytl" = "they'll"
"llt" = "totally"
"ld" = "tell"
"lds" = "tells"
"am" = "am"
"my" = "my"
"his" = "his"
"i" = "I"
"o" = "on"
"n" = "no"
"nn" = "none"
"js" = "just"
"nv" = "never"
"evy" = "every"
"p" = "people"
"pec" = "place"
"pe" = "person"
"pey" = "personally"
"rrm" = "remember"
"bv" = "believe"
"her" = "her"
"t" = "the"
"ad" = "add"
"lay" = "lay"
"u" = "you"
"q" = "yes"
"th" = "that"
"f" = "for"
"bu" = "but"
"ar" = "are"
"nt" = "not"
"ur" = "your"
"urs" = "yours"
"ure" = "yourself"
"al" = "all"
"hv" = "have"
"ghi" = "having"
"aw" = "was"
"awl" = "wasn't"
"wht" = "with"
"ts" = "this"
"wt" = "what"
"wj" = "won't"
"ty" = "they"
"wn" = "when"
"c" = "can"
"kw" = "know"
"kwn" = "known"
"kwg" = "knowing"
"klw" = "knowledge"
"oe" = "one"
"te" = "there"
"tee" = "there's"
"lk" = "like"
"dlk" = "dislike"
"wi" = "will"
"wg" = "willing"
"weg" = "weight"
"ig" = "it's"
"dn" = "don't"
"im" = "I'm"
"iv" = "I've"
"lf" = "life"
"lfm" = "lifetime"
"fm" = "from"
"frm" = "form"
"tm" = "time"
"tmm" = "tomorrow"
"ow" = "who"
"emm" = "enemy"
"ou" = "out"
"m" = "them"
"ggn" = "going"
"ab" = "about"
"mr" = "more"
"yo" = "you're"
"mq" = "maybe"
"pvy" = "previously"
"hd" = "had"
"hdd" = "hadn't"
"ejo" = "enjoy"
"fw" = "forward"
"rj" = "our"
"ly" = "only"
"hw" = "how"
"tg" = "thing"
"g" = "get"
"eg" = "enough"
"se" = "see"
"rw" = "were"
"wdk" = "word"
"wrl" = "world"
"wrls" = "worlds"
"lv" = "live"
"ov" = "love"
"jt" = "than"
"ei" = "their"
"bj" = "because"
"bk" = "back"
"bl" = "black"
"bh" = "both"
"bo" = "before"
"tk" = "think"
"tks" = "thinks"
"tkg" = "thinking"
"mk" = "make"
"mkg" = "making"
"mks" = "makes"
"e" = "then"
"sm" = "some"
"smb" = "somebody"
"sg" = "something"
"stm" = "sometime"
"sstm" = "sometimes"
"sw" = "somewhere"
"sho" = "somehow"
"som" = "someone"
"skl" = "skill"
"lsj" = "still"
"sng" = "single"
"pbb" = "problem"
"pl" = "loop"
"bn" = "been"
"ej" = "end"
"ev" = "even"
"evu" = "ever"
"wy" = "way"
"fe" = "feel"
"fg" = "feeling"
"fgs" = "feelings"
"fes" = "fees"
"wyy" = "away"
"wly" = "always"
"wys" = "Ways"
"gts" = "things"
"hm" = "him"
"cu" = "could"
"cou" = "continue"
"wnt" = "want"
"wng" = "wanting"
"dy" = "day"
"dys" = "days"
"hs" = "has"
"dig" = "dig"
"dng" = "doing"
"oj" = "other"
"ojw" = "otherwise"
"ojs" = "others"
"aj" = "another"
"dif" = "different"
"ys" = "yes"
"ye" = "you're"
"b" = "be"
"yv" = "you've"
"Yv" = "You've"
"d" = "and"
"r" = "are"
"dk" = "did"
"ng" = "nothing"
"ak" = "ask"
"gr" = "great"
"gry" = "greatly"
"mtt" = "matter"
"mtts" = "matters"
"ch" = "change"
"chd" = "changed"
"cc" = "chance"
"ccs" = "chance"
"ec" = "each"
"af" = "after"
"wv" = "we've"
"wu" = "would"
"wuv" = "would've"
"wun" = "wouldn't"
"lg" = "long"
"lng" = "longer"
"eyg" = "everything"
"erb" = "everybody"
"dnb" = "nobody"
"eor" = "everyone"
"ewh" = "everywhere"
"hn" = "haven't"
"bhv" = "behave"
"rt" = "aren't"
"cj" = "once"
"cn" = "can't"
"cnn" = "cannot"
"sd" = "said"
"dt" = "didn't"
"sad" = "sad"
"ul" = "you'll"
"en" = "need"
"ths" = "that's"
"wrr" = "we're"
"dfy" = "differently"
"dfc" = "difficult"
"dfu" = "difficulty"
"nx" = "next"
"ox" = "own"
"ay" = "any"
"ayo" = "anymore"
"v" = "very"
"gj" = "give"
"gjj" = "given"
"gsj" = "gives"
"va" = "gave"
"s" = "these"
"ag" = "anything"
"ug" = "young"
"ue" = "use"
"whr" = "where"
"md" = "made"
"sn" = "isn't"
"two" = "two"
"wut" = "without"
"wts" = "what's"
"ri" = "right"
"fj" = "find"
"fjj" = "finding"
"tu" = "too"
"tp" = "top"
"lt" = "those"
"il" = "I'll"
"ill" = "ill"
"yrs" = "years"
"yr" = "year"
"wti" = "white"
"whl" = "while"
"bt" = "better"
"btn" = "button"
"h" = "here"
"hrs" = "here's"
"tyy" = "they're"
"cun" = "couldn't"
"avo" = "above"
"mv" = "move"
"mvg" = "moving"
"mvs" = "moves"
"agi" = "again"
"tag" = "tag"
"sag" = "sag"
"nag" = "nag"
"sat" = "sat"
"gv" = "govern"
"agj" = "against"
"ke" = "knew"
"kws" = "knows"
"gd" = "good"
"stl" = "list"
"lsn" = "listen"
"gdy" = "goodbye"
"shl" = "should"
"bw" = "between"
"dw" = "down"
"sem" = "seem"
"wc" = "which"
"mo" = "most"
"mu" = "must"
"hev" = "however"
"kp" = "keep"
"kps" = "keeps"
"le" = "leave"
"les" = "leave"
"lgh" = "leaving"
"leg" = "leg"
"lei" = "lie"
"evl" = "level"
"re" = "over"
"sty" = "system"
"trh" = "through"
"ao" = "also"
"mc" = "much"
"sc" = "since"
"sk" = "such"
"hot" = "hot"
"tgh" = "through"
"sin" = "sin"
"ji" = "interest"
"jig" = "interesting"
"jid" = "interested"
"jic" = "increase"
"nm" = "name"
"bm" = "become"
"mba" = "became"
"nmb" = "number"
"gal" = "gal"
"lar" = "large"
"glr" = "general"
"ltt" = "little"
"sst" = "state"
"sstt" = "states"
"set" = "set"
"fs" = "first"
"rp" = "replace"
"pmg" = "program"
"hcl" = "child"
"she" = "she"
"say" = "say"
"man" = "man"
"hhm" = "human"
"mw" = "many"
"men" = "men"
"new" = "new"
"k" = "take"
"kk" = "taking"
"kq" = "takes"
"com" = "com"
"fh" = "come"
"fhh" = "coming"
"hld" = "hold"
"wrk" = "work"
"voe" = "over"
"hg" = "high"
"nnt" = "nation"
"pvd" = "develop"
"byo" = "boy"
"bey" = "beyond"
"dby" = "body"
"sug" = "guess"
"och" = "choice"
"rrh" = "rather"
"ud" = "under"
"fk" = "fake"
"smf" = "same"
"bgk" = "background"
"rau" = "around"
"mdd" = "mined"
"big" = "big"
"ngh" = "night"
"tth" = "thought"
"bi" = "begin"
"pn" = "point"
"ee" = "eye"
"ees" = "eyes"
"dds" = "does"
"let" = "let"
"bp" = "public"
"pv" = "private"
"fll" = "follow"
"ffl" = "following"
"pso" = "possible"
"pyo" = "possibly"
"prr" = "probably"
"cur" = "current"
"cuu" = "currently"
"lc" = "clear"
"lcy" = "clearly"
"cln" = "control"
"mps" = "impossible"
"msl" = "simple"
"ln" = "line"
"rn" = "return"
"sb" = "small"
"rnn" = "\r\n"
"rnrn" = "\r\n\r\n"
"rly" = "really"
"ery" = "ready"
"dly" = "already"
"pg" = "page"
"gk" = "group"
"udt" = "understand"
"udts" = "understands"
"udtg" = "understanding"
