[general]
auto_append = false
buffer_size = -1

[ipc]
ipc_enabled_commands = [
  "mc",  # activate normal casing
  "sc",  # activate snake_casing
  "pm",  # activate ProperCasing
  "cm",  # activate camelCasing
  "us",  # activate UPPER_SNAKE_CASING
  "cb",  # clear buffer
  "sm",  # set main buffer
  "sr",  # set right buffer
  # "rl",  # reload config
  # "rs",  # restart program
]

[chunking]
chunking_type = "last"
new_chunks_only = true

[code]
spacing_type = "new"
assumed_casing = "normal"
space_on_new = false

[while_down]
windows = "clear_buffer"
ctrl = "clear_buffer"

[chips]
"rl" = ["reload_config"]
"-" = ["kebab-case-mode"]
# "nm" = ["normal case mode"]
"_" = ["snake_case_mode"]
"__" = ["UPPER_SNAKE_CASE_MODE"]
".." = ["backspace", ".", ".", ".", "space"]
"pm" = ["ProperCaseMode"]
"cmm" = ["camelCaseMode"]
"restr" = ["restart"]
"'s" = ["backspace", "'", "s", "space"]
"'t" = ["backspace", "n", "'", "t", "space"]
"'l" = ["backspace", "'", "l", "l", "space"]
"'d" = ["backspace", "'", "d", "space"]
"at" = "at"
"it" = "it"
"in" = "in"
"is" = "is"
xk = "start"
xks = "starts"
sidn = "inside"
lm = "limit"
lim = "limits"
limt = "limitation"
limts = "limitations"
rog = "recognize"
roc = "rock"
elep = "elephant"
wdd = "we'd"
"of" = "of"
"to" = "to"
"so" = "so"
"be" = "be"
"into" = "into"
"do" = "do"
"us" = "us"
"an" = "an"
"by" = "by"
"up" = "up"
"or" = "or"
"go" = "go"
"sog" = "goes"
"gm" = "got"
"ggm" = "game"
"wel" = "well"
"lak" = "look"
"lakg" = "looking"
"lakd" = "looked"
"laks" = "looks"
"mgh" = "might"
"iig" = "imagine"
"iigg" = "imagining"
"mck" = "magic"
bnv = "believing"
"hpp" = "happen"
"hpd" = "happen"
"hpps" = "happens"
shp = "push"
"pf" = "plan"
"pfs" = "plans"
rps = "press"
"eyy" = "empty"
dcn = "decision"
dcns = "decisions"
"ety" = "yet"
"pac" = "accept"
"pacg" = "accepting"
xc = "excel"
"mee" = "mean"
"hha" = "hate"
"maa" = "may"
"whh" = "why"
"itt" = "its"
"bnn" = "being"
"bns" = "beings"
"hht" = "heart"
"hhts" = "hearts"
"he" = "he"
"me" = "me"
"if" = "if"
"load" = "load"
"lrd" = "reload"
"we" = "we"
"as" = "as"
"ytl" = "they'll"
"llt" = "totally"
"ld" = "tell"
"ldg" = "telling"
"fhi" = "fight"
"fho" = "fought"
"fhg" = "fighting"
"lds" = "tells"
"am" = "am"
"my" = "my"
"his" = "his"
"i" = "I"
"o" = "on"
"n" = "no"
"nn" = "none"
"js" = "just"
"nv" = "never"
"evy" = "every"
"fvy" = "forevery"
"p" = "people"
"pec" = "place"
"pe" = "person"
"pey" = "personally"
"rrm" = "remember"
"bv" = "believe"
"her" = "her"
"t" = "the"
"ad" = "add"
"lay" = "lay"
"u" = "you"
"q" = "yes"
"th" = "that"
"f" = "for"
"feg" = "forget"
"fog" = "fog"
"bu" = "but"
"ar" = "are"
"nt" = "not"
"ur" = "your"
"urs" = "yours"
"ure" = "yourself"
"urv" = "yourselves"
"al" = "all"
"hv" = "have"
"ghi" = "having"
"aw" = "was"
"awl" = "wasn't"
"wht" = "with"
"ts" = "this"
"wt" = "what"
"wj" = "won't"
"ty" = "they"
"wn" = "when"
"wnv" = "whenever"
"whv" = "wherever"
# not using WTV because it's all one hand
# plus there is a TV channel named that
"wjv" = "whatever"
"c" = "can"
"kw" = "know"
"kwn" = "known"
"kwg" = "knowing"
"klw" = "knowledge"
"oe" = "one"
"oes" = "one's"
"occ" = "once"
"te" = "there"
"tfe" = "therefore"
"tee" = "there's"
"lk" = "like"
"dlk" = "dislike"
"wi" = "will"
"wg" = "willing"
"weg" = "weight"
"ig" = "it's"
"dn" = "don't"
"im" = "I'm"
"iv" = "I've"
"lf" = "life"
"lfm" = "lifetime"
"fm" = "from"
"frm" = "form"
"tm" = "time"
"tmm" = "tomorrow"
"ow" = "who"
"emm" = "enemy"
"ou" = "out"
"m" = "them"
"tml" = "themself"
"lvm" = "themselves"
uuf = "future"
blg = "belong"
blgs = "belongs"
"ggn" = "going"
"ab" = "about"
"mr" = "more"
"yo" = "you're"
"mq" = "maybe"
"pvy" = "previously"
"pri" = "print"
"nrp" = "present"
"hd" = "had"
"hdd" = "hadn't"
"ejo" = "enjoy"
eogj = "enjoying"
"fw" = "forward"
"rj" = "our"
"ly" = "only"
"hw" = "how"
"tg" = "thing"
"g" = "get"
"eg" = "enough"
"se" = "see"
"rw" = "were"
"wkj" = "word"
"wrl" = "world"
"wrls" = "worlds"
"lv" = "live"
"lvs" = "lives"
"ov" = "love"
"ovv" = "love"
"jt" = "than"
"ei" = "their"
"bj" = "because"
bk = "back"
bks = "backs"
"oub" = "outbreak"
"oubs" = "outbreaks"
"bl" = "black"
"bh" = "both"
"bo" = "before"
"tk" = "think"
"tks" = "thinks"
"tkg" = "thinking"
"mk" = "make"
"mkg" = "making"
"mks" = "makes"
"e" = "then"
"sm" = "some"
"sby" = "somebody"
"ssby" = "somebody's"
tui = "tui"
utn = "until"
"sg" = "something"
"stm" = "sometime"
"sstm" = "sometimes"
"sw" = "somewhere"
"sho" = "somehow"
"som" = "someone"
smw = "somewhat"
"rie" = "realize"
wln = "wanted"
"swh" = "show"
"swhs" = "shows"
"skl" = "skill"
"lsj" = "still"
"sng" = "single"
"pbb" = "problem"
"pl" = "loop"
"bn" = "been"
"ej" = "end"
"ejs" = "ends"
"ev" = "even"
"evu" = "ever"
"wy" = "way"
"fe" = "feel"
"fej" = "feels"
"pop" = "pop"
"opps" = "opposite"
sitg = "gist"
sgg = "sitting"
ssg = "sit"
"fg" = "feeling"
epp = "experience"
epps = "experiences"
tbb = "trouble"
tbl = "table"
"fgs" = "feelings"
"fes" = "fees"
"wwy" = "away"
"wly" = "always"
"wys" = "Ways"
"gts" = "things"
"hm" = "him"
"cu" = "could"
"cou" = "continue"
"wnt" = "want"
"wng" = "wanting"
"dy" = "day"
"dys" = "days"
"hs" = "has"
"dig" = "dig"
"dng" = "doing"
"oj" = "other"
"ojw" = "otherwise"
"ojs" = "others"
"aj" = "another"
"dif" = "different"
"ys" = "yes"
"ye" = "you're"
"b" = "be"
"yv" = "you've"
"Yv" = "You've"
"d" = "and"
"r" = "are"
"dk" = "did"
"ng" = "nothing"
"ak" = "ask"
"gr" = "great"
"grr" = "greater"
exm = "example"
"gry" = "greatly"
pnc = "principle"
pncs = "principles"
jdm = "judgment"
jdms = "judgments"
"grs" = "greats"
"gre" = "greatest"
"mtt" = "matter"
"mtts" = "matters"
"ch" = "change"
"chd" = "changed"
"cc" = "chance"
"ccs" = "chances"
scr = "scare"
scrd = "scared"
sdr = "sacred"
"ec" = "each"
"af" = "after"
"wv" = "we've"
"wu" = "would"
rqm = "requirement"
rqs = "requirements"
"wuv" = "would've"
"wun" = "wouldn't"
"lg" = "long"
"lgs" = "long's"
"lng" = "longer"
"eyg" = "everything"
"erb" = "everybody"
"dnb" = "nobody"
"eoe" = "everyone"
"ewh" = "everywhere"
"hn" = "haven't"
"bhv" = "behave"
"rt" = "aren't"
"cj" = "once"
"cn" = "can't"
"cnn" = "cannot"
"sd" = "said"
"dt" = "didn't"
"sad" = "sad"
"ul" = "you'll"
"en" = "need"
"ens" = "needs"
"lrn" = "learn"
"lrg" = "learning"
"ths" = "that's"
"wrr" = "we're"
"dfy" = "differently"
"dfc" = "difficult"
"dfcs" = "difficulties"
"dfu" = "difficulty"
"nx" = "next"
"ox" = "own"
"ay" = "any"
"ayo" = "anymore"
"v" = "very"
"gj" = "give"
"gjj" = "given"
"gsj" = "gives"
"va" = "gave"
"s" = "these"
"ag" = "anything"
"ug" = "young"
"ue" = "use"
"whr" = "where"
"md" = "made"
"sn" = "isn't"
"two" = "two"
"wut" = "without"
"wts" = "what's"
"ri" = "right"
"fj" = "find"
"fjj" = "finding"
"tu" = "too"
"tp" = "top"
"lt" = "those"
"il" = "I'll"
"ill" = "ill"
"yrs" = "years"
"yr" = "year"
"wti" = "white"
"whl" = "while"
"bt" = "better"
"btn" = "button"
"h" = "here"
"hrs" = "here's"
"tyy" = "they're"
"cun" = "couldn't"
"avo" = "above"
"mv" = "move"
"mvd" = "moved"
till = "till"
glj = "it'll"
"mvg" = "moving"
"mvs" = "moves"
"agi" = "again"
"tag" = "tag"
"nag" = "nag"
"sat" = "sat"
"gv" = "govern"
"agj" = "against"
"ke" = "knew"
"kws" = "knows"
"gd" = "good"
"stl" = "list"
"lsn" = "listen"
"gdy" = "goodbye"
"shl" = "should"
"bw" = "between"
"dw" = "down"
"sem" = "seem"
"mds" = "seemed"
eih = "either"
rmn = "remain"
"sems" = "seems"
"wc" = "which"
"mo" = "most"
"moy" = "mostly"
"lam" = "almost"
"mu" = "must"
"hev" = "however"
"kp" = "keep"
"kpg" = "keeping"
"kps" = "keeps"
"le" = "leave"
"les" = "less"
ll = "else"
"lgh" = "leaving"
"leg" = "leg"
"lei" = "lie"
"evl" = "level"
"re" = "over"
"sty" = "system"
"trh" = "through"
"ao" = "also"
"mc" = "much"
"sc" = "since"
"sk" = "such"
"sdc" = "succeed"
sdu = "sudden"
"dey" = "destroy"
"ple" = "please"
"hot" = "hot"
tgh = "through"
tghu = "throughout"
hut = "hut"
gou = "tough"
prea = "reap"
repp = "repeat"
repps = "repeats"
reppg = "repeating"
preg = "grep"

"sin" = "sin"
"ji" = "interest"
"jig" = "interesting"
"jid" = "interested"
"jic" = "increase"
"jib" = "incredible"
"nm" = "name"
hpo = "hop"
hho = "hope"
"dnm" = "named"
"snm" = "names"
"bm" = "become"
"bms" = "becomes"
"mba" = "became"
"mm" = "number"
"mmb" = "unnumbered"
"gal" = "gal"
"lar" = "large"
"llg" = "general"
"ltt" = "little"
"sst" = "state"
"usst" = "upstate"
"sstt" = "states"
"set" = "set"
"fs" = "first"
"rp" = "replace"
"pmg" = "program"
"hcl" = "child"
"she" = "she"
"say" = "say"
"man" = "man"
"hhm" = "human"
"mw" = "many"
"men" = "men"
"new" = "new"
"k" = "take"
"kk" = "taking"
"kq" = "takes"
"com" = "com"
"fh" = "come"
"fhs" = "comes"
"fhh" = "coming"
"hld" = "hold"
dgg = "danger"
dggs = "dangers"
"wrk" = "work"
sck = "stack"
sckd = "stacked"
cla = "call"
clad = "called"
cel = "cell"
# "last" = "last" salt
sglt = "lasting"
rcc = "respect"
rccs = "respects"
lasg = "glass"
"wrks" = "works"
"exc" = "exact"
"excl" = "exact"
"ejn" = "enter"
"eng " = "entering"
"voe" = "over"
"hg" = "high"
"hgs" = "highs"
"hhg" = "highest"
"hgg" = "higher"
"nnt" = "nation"
"nnts" = "nation's"
"byo" = "boy"
"bey" = "beyond"
"dby" = "body"
"sug" = "guess"
"och" = "choice"
"ochs" = "choices"
"rrh" = "rather"
"ud" = "under"
"fk" = "fake"
"smf" = "same"
"bgk" = "background"
"rau" = "around"
"mdd" = "mined"
"bbi" = "big"
"bbg" = "bigger"
rrd = "regard"
"ngh" = "night"
"tth" = "thought"
"tths" = "thoughts"
"bi" = "begin"
"bii" = "beginning"
"pn" = "point"
"pns" = "points"
"ppr" = "prison"
"pprs" = "prisons"
"trk" = "trick"
"trks" = "tricks"
"ee" = "eye"
# "eey" = "eyes"
"dds" = "does"
"let" = "let"
"bp" = "public"
"pv" = "private"
"fll" = "follow"
"fls" = "follows"
"ffl" = "following"
"pso" = "possible"
"pyo" = "possibly"
sob = "sob"
pyb = "possibilitie"
pybs = "possibilities"
"prr" = "probably"
"cur" = "current"
"cuu" = "currently"
"lc" = "clear"
"lcy" = "clearly"
"cln" = "control"
"mps" = "impossible"
"gcm" = [
  "g",
  "i",
  "t",
  " ",
  "c",
  "l",
  "o",
  "n",
  "e",
  " ",
  "-",
  "m",
  " ",
  '"',
  '"',
  "left"
]
"msl" = "simple"
"ln" = "line"
"rn" = "return"
"sb" = "small"
"rnn" = "\r\n"
"rnrn" = "\r\n\r\n"
"rly" = "really"
"ery" = "ready"
zp = "PRINT_PLZ"
"dly" = "already"
"pg" = "page"
"gk" = "group"
"gks" = "groups"
mmr = "miner"
mms = "miners"
"rnng" = "running"
rjs = "ourselves"
"udt" = "understand"
# "dust" = "Understands" dust or stud
"aay" = "anyway"
"odtu" = "understood"
innc = "innocent"
incc = "innocence"
"duo" = "duo"
"tuu" = "truth"
"aaw" = "anywhere"
"ncs" = "necessary"
"kdr" = "dark"
"dor" = "rod"
wat = "water"
wyt = "watery"
ccl = "cancel"
"door" = "door"
ufo = "ufo"
fodu = "found"
"comm" = "communication"
"ccm" = "common"
"cmms" = "communications"
"cmmg" = "communicating"
"inte" = "interrupt"
"seni" = "interrupts"
"kdrs" = "darkness"
"udtg" = "understanding"
try = "try"
tyg = "trying"
fr = "free"
xj = "fix"
six = "six"
"phe" = "perhaps"
"pla" = "pleasure"
"wp" = "power"
"wpf" = "powerful"
prc = "price"
"prcn" = "presence"
hu = "house"
shu = "houses"
hug = "hug"
hue = "hue"
ely = "early"
cop = "cop"
plc = "complicate"
plcd = "complicated"
plcs = "complicates"
coo = "choose"
mys = "myself"
sly = "simply"
spl = "simple"
sim = "sim"
mss = "miss"
mssd = "missed"
"dmm" = "dimension"
"dmms" = "dimensions"
rope = "rope"
ssp = "response"
see = "see"
eel = "eel"
dfly = "definitely"
mtk = "mistake"
mtks = "mistakes"
pssn = "passion"
ck = "create"
dgu = "dug"
rvv = "revive"
sff = "suffer"
sffg = "suffering"
ayc = "actually"
htl = "that'll"
hor = "horizontal"
hat = "hat"
drg = "during"
wri = "write"
lat = "late"
svn = "version"
noa = "anyone"
fil = "fill"
fas = "false"
fal = "final"
cll = "close"
"pvd" = "develop"
ddp = "developed"
vd = "video"
ghc = "ghc"
lgc = "challenge"
lgcs = "challenges"
ntt = "motion"
aq = "acquire"
wrg = "warning"
suv = "SUV"
uiv = "universal"
oit = "omit"
oimt = "omitted"
pet = "pet"
excp = "except"
sdyy = "someday"
sugg = "suggest"
cup = "cup"
pur = "particular"
wdn = "wonder"
wdnf = "wonderful"
# "l." = "longtext."
